import cloudinary from "@/config/cloudinary";

// ─── Google Veo 3.1 image-to-video (Gemini API) ──────────────────────────────────
// Animates an approved scene image into a short cinematic clip. Async: submit a
// long-running operation, poll until done, then re-host the result on Cloudinary
// (the Gemini video URI expires in ~2 days). Audio is always generated by Veo but we
// mute the clip in JSON2Video — our ElevenLabs/HeyGen track stays the master audio.
//
// REST (generativelanguage v1beta):
//   POST /models/{model}:predictLongRunning   → { name: operation }
//   GET  /{operation}                          → { done, response.generateVideoResponse.generatedSamples[0].video.uri }

const GENAI_BASE = "https://generativelanguage.googleapis.com/v1beta";

export type VeoTier = "lite" | "fast" | "standard";

export const VEO_MODELS: Record<VeoTier, string> = {
  lite:     "veo-3.1-lite-generate-preview",
  fast:     "veo-3.1-fast-generate-preview",
  standard: "veo-3.1-generate-preview",
};

// $/sec of generated output — used for the in-app cost estimate.
export const VEO_RATE_PER_SEC: Record<VeoTier, number> = { lite: 0.05, fast: 0.15, standard: 0.40 };

function getApiKey(): string {
  const k = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!k) throw new Error("GEMINI_API_KEY is not configured — Veo needs a billed Gemini API key.");
  return k;
}

// Tame, motion-focused prompt that discourages the morphing/warping artifacts that
// image-to-video is prone to.
export function buildVeoPrompt(imageConcept: string): string {
  const c = (imageConcept ?? "").trim() || "the scene";
  return `Subtle, photorealistic cinematic motion. ${c}. Gentle natural movement and a slow camera push-in; keep faces and hands stable and lifelike; no morphing, no distortion, no text or captions.`;
}

// Veo only outputs 16:9 or 9:16. Our scene images are 2:3 (taller-but-wider than 9:16), so
// feeding them as-is makes Veo letterbox them with black bars. Crop the Cloudinary image to a
// true 9:16 (smart gravity keeps the subject) so the generated clip fills the vertical frame.
function to9x16(imageUrl: string): string {
  return imageUrl.includes("/image/upload/")
    ? imageUrl.replace("/image/upload/", "/image/upload/c_fill,ar_9:16,g_auto,w_1080/")
    : imageUrl;
}

async function imageUrlToInlineData(imageUrl: string): Promise<{ mimeType: string; data: string }> {
  const res = await fetch(to9x16(imageUrl));
  if (!res.ok) throw new Error(`Could not fetch the scene image (HTTP ${res.status})`);
  const mimeType = (res.headers.get("content-type") ?? "image/png").split(";")[0];
  const data = Buffer.from(await res.arrayBuffer()).toString("base64");
  return { mimeType, data };
}

export async function submitSceneClip(opts: {
  imageUrl: string;
  imageConcept: string;
  tier?: VeoTier;
  durationSec?: 4 | 6 | 8;
  aspectRatio?: "9:16" | "16:9";
}): Promise<{ operationName: string }> {
  const key   = getApiKey();
  const model = VEO_MODELS[opts.tier ?? "lite"];
  const image = await imageUrlToInlineData(opts.imageUrl);

  const body = {
    instances: [{
      prompt: buildVeoPrompt(opts.imageConcept),
      // predictLongRunning uses the Vertex-style image field (NOT inlineData).
      image: { bytesBase64Encoded: image.data, mimeType: image.mimeType },
    }],
    parameters: {
      aspectRatio:      opts.aspectRatio ?? "9:16",
      resolution:       "720p",
      durationSeconds:  opts.durationSec ?? 6,
      personGeneration: "allow_adult",
      sampleCount:      1,
    },
  };

  const res = await fetch(`${GENAI_BASE}/models/${model}:predictLongRunning`, {
    method:  "POST",
    headers: { "x-goog-api-key": key, "Content-Type": "application/json" },
    body:    JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok || !data?.name) {
    throw new Error(`Veo submit failed (HTTP ${res.status}): ${data?.error?.message ?? "unknown error"}`);
  }
  return { operationName: String(data.name) };
}

export async function getSceneClipStatus(
  operationName: string,
  category?: string
): Promise<{ status: "running" | "done"; videoUrl?: string }> {
  const key = getApiKey();

  const res  = await fetch(`${GENAI_BASE}/${operationName}`, { headers: { "x-goog-api-key": key } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`Veo status check failed (HTTP ${res.status}): ${data?.error?.message ?? "unknown error"}`);

  if (!data.done) return { status: "running" };
  if (data.error) throw new Error(`Veo render error: ${data.error.message ?? "unknown"}`);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const r = (data.response ?? {}) as any;
  const uri: string | undefined =
    r?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri ??
    r?.generateVideoResponse?.samples?.[0]?.video?.uri ??
    r?.videos?.[0]?.uri;

  if (!uri) {
    const blocked = r?.generateVideoResponse?.raiMediaFilteredReasons?.[0];
    throw new Error(blocked ? `Veo blocked this clip: ${blocked}` : "Veo finished but returned no video. Try re-animating.");
  }

  // Download with the key (URI expires in ~2 days), then re-host on Cloudinary.
  const vid = await fetch(uri, { headers: { "x-goog-api-key": key }, redirect: "follow" });
  if (!vid.ok) throw new Error(`Could not download the Veo clip (HTTP ${vid.status})`);
  const bytes = Buffer.from(await vid.arrayBuffer());

  const videoUrl = await new Promise<string>((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder: `social-media/${category ?? "general"}/veo`, resource_type: "video" },
      (err, result) => (err || !result ? reject(err ?? new Error("Cloudinary upload failed")) : resolve(result.secure_url))
    );
    stream.end(bytes);
  });

  return { status: "done", videoUrl };
}
