import { defineType, type Rule } from 'sanity'
import { PresentationIcon } from '@sanity/icons'
import { field, pairString, pairText, collapsed } from './helpers'

// Singleton document (fixed _id: "iulPresentation") holding the entire
// /iul/presentation slide deck. Every user-visible string is an EN+ES field
// pair so both languages are edited side by side and can never drift.
export const iulPresentationType = defineType({
  name: 'iulPresentation',
  title: 'IUL Presentation',
  type: 'document',
  icon: PresentationIcon,
  groups: [
    { name: 'slides', title: 'Slides', default: true },
    { name: 'ui', title: 'Page UI' },
    { name: 'labels', title: 'Shared Labels' },
    { name: 'meta', title: 'SEO' },
  ],
  fields: [
    field({
      name: 'title',
      type: 'string',
      title: 'Internal Title',
      group: 'slides',
      initialValue: 'IUL Presentation',
      validation: (rule: Rule) => rule.required(),
    }),
    field({
      name: 'slides',
      type: 'array',
      title: 'Slides',
      group: 'slides',
      description: 'Slide order here is the order shown in the presentation.',
      of: [
        { type: 'iulSlideAgent' },
        { type: 'iulSlideDiscovery' },
        { type: 'iulSlideRetirementProduct' },
        { type: 'iulSlideScenario' },
        { type: 'iulSlideBank' },
        { type: 'iulSlideBankExample' },
        { type: 'iulSlideBankCosts' },
        { type: 'iulSlideBankTeaser' },
        { type: 'iulSlideIulHero' },
        { type: 'iulSlideIulWho' },
        { type: 'iulSlideIulComparison' },
        { type: 'iulSlideIulStructure' },
        { type: 'iulSlideIulIndexing' },
        { type: 'iulSlideIulTerms' },
        { type: 'iulSlideIulNotInvested' },
        { type: 'iulSlideIulHowItWorks' },
        { type: 'iulSlideIulIllustrationCta' },
        { type: 'iulSlideCompany' },
      ],
    }),
    field({
      name: 'ui',
      type: 'object',
      title: 'Page UI',
      group: 'ui',
      options: collapsed,
      fields: [
        ...pairString('title', 'Page Title'),
        ...pairString('backButton', 'Back Button'),
        ...pairString('stepperPresentation', 'Stepper: Presentation'),
        ...pairString('stepperApplication', 'Stepper: Application'),
        ...pairString('stepperReferrals', 'Stepper: Referrals'),
        ...pairString('fullscreenEnter', 'Fullscreen: Enter'),
        ...pairString('fullscreenExit', 'Fullscreen: Exit'),
        ...pairString('intakeTitle', 'Intake CTA: Title'),
        ...pairText('intakeDescription', 'Intake CTA: Description', 2),
        ...pairString('intakeButton', 'Intake CTA: Button'),
      ],
    }),
    field({
      name: 'labels',
      type: 'object',
      title: 'Shared Labels',
      group: 'labels',
      description: 'Labels reused across several slides (loan tables, scenario sections, etc.).',
      options: collapsed,
      fields: [
        ...pairString('contributionLimit', 'Contribution Limit'),
        ...pairString('catchUp', 'Catch-up'),
        ...pairString('advantages', 'Advantages'),
        ...pairString('disadvantages', 'Disadvantages'),
        ...pairString('situation', 'The Situation'),
        ...pairString('problem', 'The Problem'),
        ...pairString('impact', 'The Impact'),
        ...pairString('scenario', 'The Scenario'),
        ...pairString('loanDetails', 'Loan Details'),
        ...pairString('loanAmount', 'Loan Amount'),
        ...pairString('interestRate', 'Interest Rate'),
        ...pairString('term', 'Term'),
        ...pairString('monthlyPayment', 'Monthly Payment'),
        ...pairString('trueCost', 'True Cost'),
        ...pairString('totalYoullPay', "Total You'll Pay"),
        ...pairString('interestPaidToBank', 'Interest Paid to Bank'),
        ...pairString('moneyNeverSeeAgain', 'Money Never See Again'),
        ...pairString('lifetimeInterestPaid', 'Lifetime Interest Paid'),
        ...pairString('toBanksAndInstitutions', 'To Banks and Institutions'),
        ...pairString('solutionExists', 'The Solution Exists'),
      ],
    }),
    field({
      name: 'meta',
      type: 'object',
      title: 'SEO',
      group: 'meta',
      options: collapsed,
      fields: [
        ...pairString('title', 'Meta Title'),
        ...pairText('description', 'Meta Description', 2),
        ...pairString('keywords', 'Keywords'),
        field({
          name: 'imageEn',
          type: 'url',
          title: 'OG Image URL (EN)',
          description: 'Absolute URL — fed to the Cloudinary OG helper.',
        }),
        field({ name: 'imageEs', type: 'url', title: 'OG Image URL (ES)' }),
        ...pairString('imageAlt', 'OG Image Alt'),
      ],
    }),
  ],
  preview: {
    select: { title: 'title', slides: 'slides' },
    prepare({ title, slides }: { title?: string; slides?: unknown[] }) {
      return { title: title || 'IUL Presentation', subtitle: `${slides?.length ?? 0} slides` }
    },
  },
})
