/**
 * Regenerate `lib/iul-intake/data/ach-directory.generated.ts` from the FedACH participant file.
 *
 *   pnpm build:ach-directory
 *
 * ─── You will almost certainly never need to run this ───
 *
 * The Federal Reserve moved the bulk directory behind FedLine — financial institutions only — in
 * December 2018, so every public mirror is frozen on that release and re-running this produces a
 * byte-identical file. It exists so the embedded blob is reproducible rather than a binary someone
 * has to take on faith, and so there is somewhere obvious to point a fresher source if one appears.
 *
 * ─── What it drops, and why ───
 *
 * Records carrying a "new routing number" are retired: the institution merged and the number was
 * replaced. Roughly 1,600 of them. Suggesting a retired number would fail a premium draft, which
 * is the one outcome this whole feature exists to prevent, so they never reach the file.
 */

import { writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { resolve } from "node:path";

/** The moov-io mirror of the last public FedACH release. */
const SOURCE = "https://raw.githubusercontent.com/moov-io/fed/master/data/FedACHdir.txt";

const OUT = resolve(process.cwd(), "lib/iul-intake/data/ach-directory.generated.ts");

/**
 * Fixed-width offsets from the FedACH record layout. Written out rather than inlined because a
 * bare `line.slice(107, 127)` in the middle of a loop is unreviewable.
 */
const FIELD = {
  routingNumber: [0, 9],
  changeDate: [20, 26],
  newRoutingNumber: [26, 35],
  name: [35, 71],
  city: [107, 127],
  state: [127, 129],
} as const;

const at = (line: string, [from, to]: readonly [number, number]) =>
  line.slice(from, to).trim().replace(/\s+/g, " ");

async function main() {
  console.log(`Fetching ${SOURCE}`);
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${res.statusText}`);
  const text = await res.text();

  const byRouting = new Map<string, string>();
  let retired = 0;
  let newest = "";

  for (const line of text.split("\n")) {
    // Short lines are truncated or blank; the state field is the last thing we read.
    if (line.length < FIELD.state[1]) continue;

    const replacement = at(line, FIELD.newRoutingNumber);
    if (replacement && replacement !== "000000000") {
      retired++;
      continue;
    }

    const routingNumber = at(line, FIELD.routingNumber);
    const name = at(line, FIELD.name);
    if (!/^\d{9}$/.test(routingNumber) || !name) continue;

    // Branch rows repeat their institution's number; the first one wins.
    if (byRouting.has(routingNumber)) continue;
    byRouting.set(routingNumber, `${routingNumber}\t${name}\t${at(line, FIELD.city)}\t${at(line, FIELD.state)}`);

    // MMDDYY → YYYY-MM-DD, so the vintage in the header is a fact and not a guess.
    const mmddyy = at(line, FIELD.changeDate);
    if (/^\d{6}$/.test(mmddyy)) {
      const yy = Number(mmddyy.slice(4, 6));
      const iso = `${yy >= 70 ? 1900 + yy : 2000 + yy}-${mmddyy.slice(0, 2)}-${mmddyy.slice(2, 4)}`;
      if (iso > newest) newest = iso;
    }
  }

  const tsv = [...byRouting.keys()].sort().map((k) => byRouting.get(k)!).join("\n");
  const base64 = gzipSync(Buffer.from(tsv, "utf8"), { level: 9 }).toString("base64");
  const chunks = base64.match(/.{1,100}/g) ?? [];

  const file = `/**
 * The FedACH participant directory, embedded.
 *
 * AUTO-GENERATED by \`scripts/build-ach-directory.ts\` — do not edit by hand.
 *
 * Records:  ${byRouting.size.toLocaleString("en-US")} institutions (routing number, name, city, state)
 * Source:   FedACH participant file, via the moov-io/fed public mirror
 * Vintage:  ${newest} — the last public release. The Federal Reserve moved the
 *           bulk file behind FedLine (financial institutions only) in December
 *           2018, which is why every public mirror stops on this date.
 *
 * Embedded as gzip+base64 rather than a file read from disk on purpose: a data
 * file has to be named in \`outputFileTracingIncludes\` for every route that reads
 * it, and a route added later that forgets the entry breaks in production only.
 * A module import cannot fail that way.
 */

/** gzip of a TSV: \`routingNumber\\tname\\tcity\\tstate\` per line, sorted by number. */
export const ACH_DIRECTORY_GZ_BASE64 = [
${chunks.map((c) => `  "${c}",`).join("\n")}
].join("");

export const ACH_DIRECTORY_META = {
  records: ${byRouting.size},
  vintage: "${newest}",
  source: "https://github.com/moov-io/fed (data/FedACHdir.txt)",
} as const;
`;

  writeFileSync(OUT, file, "utf8");
  console.log(`Kept ${byRouting.size} institutions, dropped ${retired} retired numbers.`);
  console.log(`Newest change date: ${newest}`);
  console.log(`Wrote ${OUT} (${Math.round(file.length / 1024)} KB)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
